version: '2'

services:
  web:
    container_name: cobooks-nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    links:
      - php
      - memcached
    volumes:
      - ../project:/project
  php:
    container_name: cobooks-php
    build:
      context: ./php7-fpm
    links:
      - mysql
      - memcached
    volumes:
      - ../project:/project
  memcached:
    image: memcached:latest
    container_name: crm-memcached
  mysql:
    image: mysql:latest
    container_name: cobooks-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-storage-engine=INNODB --max-sp-recursion-depth=100 --max-allowed-packet=20M --thread-stack=512K --optimizer-search-depth=0 --sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
        MYSQL_DATABASE: cobooks
        MYSQL_USER: test
        MYSQL_PASSWORD: v88THWDHV8
        MYSQL_ROOT_PASSWORD: wtXrJYd1tB